;ilość etapów wykonanych automatycznie
etapy=100
;wyświetlaj podgląd: brak/okno
widok=okno
;folder do zapisywania wyników
wyniki=testy
;częstotliwość zapisywania wyników, co ile etapów ma zapisywać; musi być większe od 0
zapisy=3